title: Clément Hardy
url: "https://clementhardy.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Jekyll template by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: ""
 - name: "Work"
   link: "projects"
 - name: "Resume"
   link: "resume"
 - name: "Contact"
   link: "mailto:clement.hardy@enpc.fr"
